"""empty message

Revision ID: 1939435a464a
Revises: 224d9f82ec23
Create Date: 2017-02-10 10:44:52.786193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1939435a464a'
down_revision = '224d9f82ec23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['email'])
    op.create_unique_constraint(None, 'permissions', ['value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
