"""empty message

Revision ID: 224d9f82ec23
Revises: ceb9bee8f04e
Create Date: 2017-02-09 15:28:24.857952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224d9f82ec23'
down_revision = 'ceb9bee8f04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('permissions', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'permissions')
    # ### end Alembic commands ###
