"""empty message

Revision ID: bbc995aada91
Revises: 
Create Date: 2017-02-21 09:59:26.541765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc995aada91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_name', sa.String(length=10), nullable=True))
    op.add_column('comments', sa.Column('project_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'project_name')
    op.drop_column('comments', 'author_name')
    # ### end Alembic commands ###
