class Config(object):
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    MAX_CONTENT_LENGTH = 100 * 1024 * 1024
    SQLALCHEMY_POOL_TIMEOUT = 900
    SQLALCHEMY_POOL_RECYCLE = 900
    SQLALCHEMY_POOL_SIZE = 300
    SQLALCHEMY_MAX_OVERFLOW = 50


def init_app(app):
    pass
